// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, QUT 2005-2010
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.3.6
// Machine:  MIL8A-316-05
// DateTime: 02.03.2020 11:26:16
// UserName: user
// Input file <SimpleYacc.y>

// options: no-lines gplex

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using QUT.Gppg;

namespace SimpleParser
{
public enum Tokens {
    error=1,EOF=2,BEGIN=3,END=4,INUM=5,BNUM=6,
    ID=7,ASSIGN=8,SEMICOLON=9,FOR=10,COMMA=11,COLON=12,
    WHILE=13,VAR=14,IF=15,ELSE=16};

// Abstract base class for GPLEX scanners
public abstract class ScanBase : AbstractScanner<int,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

public class Parser: ShiftReduceParser<int, LexLocation>
{
  // Verbatim content from SimpleYacc.y
// Ёти объ€влени€ добавл€ютс€ в класс GPPGParser, представл€ющий собой парсер, генерируемый системой gppg
    public Parser(AbstractScanner<int, LexLocation> scanner) : base(scanner) { }
  // End verbatim content from SimpleYacc.y

#pragma warning disable 649
  private static Dictionary<int, string> aliasses;
#pragma warning restore 649
  private static Rule[] rules = new Rule[23];
  private static State[] states = new State[42];
  private static string[] nonTerms = new string[] {
      "progr", "$accept", "block", "stlist", "statement", "assign", "for", "while", 
      "var", "if", "ident", "expr", "varlist", };

  static Parser() {
    states[0] = new State(new int[]{3,4},new int[]{-1,1,-3,3});
    states[1] = new State(new int[]{2,2});
    states[2] = new State(-1);
    states[3] = new State(-2);
    states[4] = new State(new int[]{7,14,3,4,10,18,13,26,14,30,15,36},new int[]{-4,5,-5,41,-6,9,-11,10,-3,16,-7,17,-8,25,-9,29,-10,35});
    states[5] = new State(new int[]{4,6,9,7});
    states[6] = new State(-15);
    states[7] = new State(new int[]{7,14,3,4,10,18,13,26,14,30,15,36},new int[]{-5,8,-6,9,-11,10,-3,16,-7,17,-8,25,-9,29,-10,35});
    states[8] = new State(-4);
    states[9] = new State(-5);
    states[10] = new State(new int[]{8,11});
    states[11] = new State(new int[]{7,14,5,15},new int[]{-12,12,-11,13});
    states[12] = new State(-12);
    states[13] = new State(-13);
    states[14] = new State(-11);
    states[15] = new State(-14);
    states[16] = new State(-6);
    states[17] = new State(-7);
    states[18] = new State(new int[]{7,14},new int[]{-11,19});
    states[19] = new State(new int[]{8,20});
    states[20] = new State(new int[]{5,21});
    states[21] = new State(new int[]{11,22});
    states[22] = new State(new int[]{5,23});
    states[23] = new State(new int[]{7,14,3,4,10,18,13,26,14,30,15,36},new int[]{-5,24,-6,9,-11,10,-3,16,-7,17,-8,25,-9,29,-10,35});
    states[24] = new State(-16);
    states[25] = new State(-8);
    states[26] = new State(new int[]{7,14,5,15},new int[]{-12,27,-11,13});
    states[27] = new State(new int[]{7,14,3,4,10,18,13,26,14,30,15,36},new int[]{-5,28,-6,9,-11,10,-3,16,-7,17,-8,25,-9,29,-10,35});
    states[28] = new State(-17);
    states[29] = new State(-9);
    states[30] = new State(new int[]{7,14},new int[]{-13,31,-11,34});
    states[31] = new State(new int[]{11,32,4,-20,9,-20,16,-20});
    states[32] = new State(new int[]{7,14},new int[]{-11,33});
    states[33] = new State(-19);
    states[34] = new State(-18);
    states[35] = new State(-10);
    states[36] = new State(new int[]{7,14,5,15},new int[]{-12,37,-11,13});
    states[37] = new State(new int[]{7,14,3,4,10,18,13,26,14,30,15,36},new int[]{-5,38,-6,9,-11,10,-3,16,-7,17,-8,25,-9,29,-10,35});
    states[38] = new State(new int[]{16,39,4,-22,9,-22});
    states[39] = new State(new int[]{7,14,3,4,10,18,13,26,14,30,15,36},new int[]{-5,40,-6,9,-11,10,-3,16,-7,17,-8,25,-9,29,-10,35});
    states[40] = new State(-21);
    states[41] = new State(-3);

    rules[1] = new Rule(-2, new int[]{-1,2});
    rules[2] = new Rule(-1, new int[]{-3});
    rules[3] = new Rule(-4, new int[]{-5});
    rules[4] = new Rule(-4, new int[]{-4,9,-5});
    rules[5] = new Rule(-5, new int[]{-6});
    rules[6] = new Rule(-5, new int[]{-3});
    rules[7] = new Rule(-5, new int[]{-7});
    rules[8] = new Rule(-5, new int[]{-8});
    rules[9] = new Rule(-5, new int[]{-9});
    rules[10] = new Rule(-5, new int[]{-10});
    rules[11] = new Rule(-11, new int[]{7});
    rules[12] = new Rule(-6, new int[]{-11,8,-12});
    rules[13] = new Rule(-12, new int[]{-11});
    rules[14] = new Rule(-12, new int[]{5});
    rules[15] = new Rule(-3, new int[]{3,-4,4});
    rules[16] = new Rule(-7, new int[]{10,-11,8,5,11,5,-5});
    rules[17] = new Rule(-8, new int[]{13,-12,-5});
    rules[18] = new Rule(-13, new int[]{-11});
    rules[19] = new Rule(-13, new int[]{-13,11,-11});
    rules[20] = new Rule(-9, new int[]{14,-13});
    rules[21] = new Rule(-10, new int[]{15,-12,-5,16,-5});
    rules[22] = new Rule(-10, new int[]{15,-12,-5});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
    switch (action)
    {
    }
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliasses != null && aliasses.ContainsKey(terminal))
        return aliasses[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

}
}
