name: GEN_DOC_DOCKER

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://pandoc/latex:2.10
        with:
          entrypoint: bin/sh
          args: |
            ls
